### ISSUE TITLE
BUG: Broken sandbox

### ISSUE THREAD

**Issue by azinit** [EliseyMartynov/fs-vue#4]
Сэндбокс падает почему-то 🤔 

https://codesandbox.io/s/github/EliseyMartynov/fs-vue/tree/master/

![image](https://user-images.githubusercontent.com/42924400/147465698-729e61a8-cb11-4920-96ff-9c90318035e4.png)

**Comment by azinit** [comment]
неплохо кста было бы сэндбокс и в ридмиху тож добавить

**Comment by EliseyMartynov** [comment]
@azinit https://github.com/vitejs/vite/issues/4463 - ну тут, к сожалению, ничего не поделать пока видимо. Такая вот шляпка с vite'ом в codesandbox у всех видимо)

**Comment by azinit** [comment]
@EliseyMartynov Дичево если так)

Но лан, если даж кодсэндбокс с vite'ом не в ладах, то тогда пусть рили в репозитории код будут смотреть

Тогда можем клозать ишьюс, спс что глянул
